# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Login Shell
source $HOME/.profile

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="crazysim"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(gem ruby git brew osx github z ant vi-mode bundler pip history-substring-search heroku vagrant virtuanenv vundle rsync pow golang pyenv)


[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

# Making sure these are in there
# System Stuff
export PATH=/usr/bin:/bin:/sbin:/usr/X11/bin:$PATH

# HomeBrew
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

# Homebrew Python
export PATH=/usr/local/share/python:$PATH


# Personal Binaries
export PATH=$HOME/bin:$PATH

# Golang Binaries
export PATH=$HOME/code/golang/bin:$PATH

export PATH=/usr/local/share/python:$PATH

export EDITOR="vim"

# Disable ZSH update prompt and be more Chrome-like and just update, damn it.
export DISABLE_UPDATE_PROMPT="true"

alias shmagnum="mosh magnum -p 60000"

eval "$(rbenv init -)"

[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc

# API Keys
source $HOME/.api_keys

export PGDATA="/usr/local/var/postgres"

# NPM utilities
export PATH="/usr/local/share/npm/bin:$PATH"

# AutoJump
[[ -f `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# alias pview="python ~/code/sr/ric/remote_capture/pickle_to_cap.py"

export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk

export SBT_OPTS='-noverify -javaagent:/Users/nelson/bin/jrebel.jar -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M'

source $ZSH/oh-my-zsh.sh

function pf_open () {
        open -a "Path Finder.app" $PWD
}

function wubi_package { curl -F package=@$1 http://wubi.local:10001/package ; }
function wubi_rawreceipt { curl -F rawreceipt=@$1 http://wubi.local:10001/rawreceipt ; }
function xing_package { curl -F package=@$1 http://xing.local:10001/package ; }
function xing_rawreceipt { curl -F rawreceipt=@$1 http://xing.local:10001/rawreceipt ; }

function unmerged_git { for k in $(git branch -a --merged|grep -v "\->"|sed "s/^..//");do echo -e $(git log -1 --pretty=format:"%Cgreen%ci %Cred%cr%Creset" "$k")\\t"$k";done|sort|less ; }

function serial38400 {
  exec 3<> /dev/cu.usbserial
  stty -f /dev/cu.usbserial speed 38400
  cat $1 >&3
  exec 3>&-
}

# Pyenv setup
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
