# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="crazysim"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(rails3 gem ruby git brew osx github autojump ant vi-mode pip)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

# Making sure these are in there
# System Stuff
export PATH=/usr/bin:/bin:/sbin:/usr/X11/bin:$PATH

# HomeBrew
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

# Homebrew Python
export PATH=/usr/local/share/python3:$PATH

# Virtualenv
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source `which virtualenvwrapper.sh`

# Personal Binaries
export PATH=$HOME/bin:$PATH

export PATH=/usr/local/share/python:$PATH

# 
export EDITOR="vim"

# Disable ZSH update prompt and be more Chrome-like and just update, damn it.
export DISABLE_UPDATE_PROMPT="true"

alias shmagnum="mosh magnum -p 60000"

eval "$(rbenv init -)"

[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc

# API Keys
source $HOME/.api_keys

export PGDATA="/usr/local/var/postgres"

# NPM utilities
export PATH="/usr/local/share/npm/bin:$PATH"

# CUDA crap
export PATH="/Developer/NVIDIA/CUDA-5.0/bin:$PATH"
# export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH

# AutoJump
[[ -f `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# alias pview="python ~/code/sr/ric/remote_capture/pickle_to_cap.py"

